site:
    title: "mutemaniac的博客"
    subtitle: "看娃·coding"
    limit: 10
    theme: theme
    lang: zh
    url: "https://mutemaniac.github.io"
    comment: username
    logo: "-/images/robin.jpg"
    # link: "{category}/{year}/{month}/{day}/{title}.html"
    # root: "/blog"

authors:
    me:
        name: "mutemaniac"
        intro: "golang/C/Docker/Java"
        avatar: "-/images/robin.jpg"

build:
    # output: "public"
    port: 8000
    # Copied files to public folder when build
    copy:
        - "source/images"
        - theme/css
        - theme/js
        - theme/favicon.ico
        - theme/robots.txt
    # Excuted command when use 'ink publish'
    publish: |
        export from_path=~/Documents/blog/blog/public/
        export to_path=~/Documents/blog/mutemaniac.github.io/
        cp -RP $from_path $to_path
        cd $to_path
        git add . -A
        git commit -m "update"
        git push origin
